### ISSUE TITLE
sitemap defaults are not being honored

### ISSUE THREAD

**Issue by nikmartin** [ExtraHop/metalsmith-sitemap#9]
I setup the sitemap plugin like:

```js
.use(sitemap({
    hostname: 'http://www.myserver.com/',
    defaults: {
      changefreq: 'monthly'
    }
  }))
```
and also have a few files with this frontmatter:

```yaml
---
template: page.hbs
title: Thank You
private: true
---
```

And the hostname IS being set, but changefreq is still set to 'daily', and the files with private:true are still being inserted into the sitemap.
